name: CI

on:
  pull_request:
    types:
      - closed

jobs:
  clean_up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log some stuff
      run: |
        cat $GITHUB_EVENT_PATH
        env | grep GITHUB

    - name: Clean up
      run: ./scripts/ci-pull-request-closed.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
