name: Run PR checks
on:
  issue_comment:
    types:
      - created
jobs:
  run_pr_checks:
    if: contains(github.event.comment.body, '/run-checks')
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - name: Run the first check
        run: |
          echo "Hey, I ran!"
