name: Run PR checks
on:
  pull_request:
    branches:
      - master
  issue_comment:
    types:
      - created
jobs:
  dispatch:
    if: contains(github.event.comment.body, '/run-checks')
    name: Run PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Run the first check
        run: |
          echo "Hey, I ran!"
