name: Handle pull requests
on:
  pull_request:
    branches:
      - master
jobs:    
  run_pr_checks:
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - name: Check perms
        id: perms
        uses: cnunciato/check-repo-perms@v0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Do a thing
        run: |
          echo "${{ steps.perms.outputs.permission }}"
