name: Handle pull requests
on:
  pull_request:
    branches:
      - master
jobs:
  check_perms:
    name: Check repo permissions
    runs-on: ubuntu-latest
    outputs:
      perms: ${{ steps.check-perms.outputs.perms }}
    steps:
      - uses: actions/checkout@v2
      - name: Check perms
        id: check-perms
        run: |
          npm install
          perms="$(node ./scripts/get-repo-perms.js)"
          echo $perms
          echo "::set-output name=perms::$perms"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run_pr_checks:
    name: Run all checks
    runs-on: self-hosted
    needs: check_perms
    if: ${{ needs.check_perms.outputs.perms == 'admin' }}
    steps:
      - name: Do a thing
        run: |
          echo "${{ needs.check_perms.outputs.perms == 'admin' }}"
          echo "${{ needs.check_perms.outputs.perms }}"
