name: Handle pull requests
on:
  pull_request:
    branches:
      - master
jobs:    
  check_repo_perms:
    name: Check repo permissions
    runs-on: ubuntu-latest
    outputs:
      perms: ${{ steps.perms.outputs.permission }}
      is_member_of_org: ${{ steps.perms.outputs.is_member_of_org }}
    steps:
      - name: Check repo permissions
        id: perms
        uses: cnunciato/check-repo-perms@v0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  run_pr_checks:
    name: Run all checks
    runs-on: self-hosted
    needs: check_repo_perms
    if: ${{ needs.check_repo_perms.outputs.is_member_of_org == 'true' }}
    steps:
      - name: Do the trusted-only thing
        run: |
          echo "Doing the thing!"
