name: Handle pull requests
on:
  pull_request:
    branches:
      - master
jobs:
  check_perms:
    name: Check repo permissions
    runs-on: ubuntu-latest
    steps:
      - name: Check perms
        uses: cnunciato/check-repo-perms@v0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  run_pr_checks:
    name: Run all checks
    runs-on: ubuntu-latest
    needs: check_perms
    steps:
      - name: Do a thing
        run: |
          echo "${{ check_perms.outputs }}"
