name: Pull Request
on:
  issue_comment:
    types:
      - created
jobs:
  dispatch:
    name: Handle Comment
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        # if: contains(github.event.comment.body, '/run-checks')
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-request
