name: Pull Request
on:
  pull_request:
    branches:
      - master
    types:
      - opened
  issue_comment:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maybe run
        run: |
          echo "running"
      - name: Actually run the checks
        if: contains(github.event.comment.body, '/run-checks')
        run: |
          echo "yay!"
