name: Handle pull requests
on:
  pull_request:
    branches:
      - master
jobs:
  check_perms:
    name: Check repo permissions
    runs-on: ubuntu-latest
    steps:
      - name: Check perms
        id: perms
        uses: cnunciato/check-repo-perms@v0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  run_pr_checks:
    name: Run all checks
    runs-on: self-hosted
    needs: check_perms
    if: ${{ needs.check_perms.outputs.perms == 'admin' }}
    steps:
      - name: Do a thing
        run: |
          echo "${{ needs.check_perms.outputs.perms == 'admin' }}"
          echo "${{ needs.check_perms.outputs.perms }}"
