name: Handle pushes
on:
  push:
    branches:
      - master
jobs:    
  run_all_checks:
    name: Run all checks
    runs-on: self-hosted
    steps:
      - name: Try to use secrets
        run: |
          echo "$SOME_SECRET"
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
