name: Handle pushes
on:
  push:
    branches:
      - master
jobs:
  check_perms:
    name: Check repo permissions
    runs-on: ubuntu-latest
    outputs:
      perms: ${{ steps.check-perms.outputs.perms }}
    steps:
      - uses: actions/checkout@v2
      - id: check-perms
        run: |
          perms="$(node ./scripts/get-repo-perms.js)"
          echo "::set-output name=perms::$perms"
  run_push_jobs:
    name: Do all the things
    needs: check_perms
    if: ${{ needs.check-perms.outputs.perms == 'admin' }}
    runs-on: self-hosted
    steps:
      - name: Do a thing
        run: |
          echo "Hey look, I did the thing!"
