name: Validate
on:
  issue_comment:
    types: [created, edited]

jobs:
  validate:
    name: Validate all the things
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request && contains( github.event.comment.body, 'do the thing' )) }}
    steps:

      - name: Run the required thing
        run: |
          echo "And I ran..."
